[default]

TELEGRAM_API_ID = "Veja qual em my.telegram.org"
TELEGRAM_API_HASH = "Veja qual em my.telegram.org"

SRC_CHAT_ID="Int com a localização do chat de base da exportação"
DST_CHAT_ID="Int com a localização do chat de destino da exportação"

# Ao final, mova este arquivo para .secrets.toml e (opcionalmente) remova esta linha
